// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {Test, console2} from "forge-std/Test.sol";
import {NexusComputeCredit} from "../../src/NexusComputeCredit.sol";

/**
 * @notice Protocol-level invariant tests.
 *
 * Invariants that must ALWAYS hold:
 *  1. NCC: totalSupply is non-negative (trivially guaranteed by ERC-20 underflow checks)
 *  2. NCC: contract ETH balance >= totalSupply * (1 - FEE/BPS)  (never insolvent)
 *  3. NCC: agentComputeSpend[a] can only grow (burned tokens are permanent)
 *
 * Foundry stateless invariant tests run the invariant_ functions after each
 * call sequence generated by the fuzzer against any contracts in the handler.
 * Because we are not deploying a full handler here, these are expressed as
 * targeted property tests that exercise sequences manually.
 */
contract NexusComputeCreditInvariants is Test {
    NexusComputeCredit public ncc;
    address public treasury = makeAddr("treasury");
    address public alice    = makeAddr("alice");
    address public bob      = makeAddr("bob");
    address public service  = makeAddr("service");

    function setUp() public {
        ncc = new NexusComputeCredit(treasury);
        ncc.authorizeService(service, true);
    }

    // -----------------------------------------------------------------------
    // Invariant: totalSupply == ETH balance + fees_sent_to_treasury
    //   Simplified: after any mint the contract holds exactly totalSupply wei.
    //   After a redeem the contract loses (principal - fee) and sends fee to
    //   treasury, so balance == remaining totalSupply exactly.
    // -----------------------------------------------------------------------
    function invariant_NCCNotInsolvent() public view {
        // The contract must always be able to cover its outstanding supply
        // (minus any fees that already left). A strict equality holds because
        // fees are deducted from ETH held, not from totalSupply. So:
        //   contract_balance + fees_paid == totalSupply_at_mint  (tracked externally)
        // Simplified check: balance can never exceed totalSupply (no free money).
        uint256 bal    = address(ncc).balance;
        uint256 supply = ncc.totalSupply();
        // After fees leave, balance < supply is expected (fees paid out).
        // What must NOT happen: balance > supply (unbacked NCC).
        assertLe(bal, supply);
    }

    // -----------------------------------------------------------------------
    // Invariant: totalSupply is always non-negative (sanity)
    // -----------------------------------------------------------------------
    function invariant_NCCSupplyNonNegative() public view {
        assert(ncc.totalSupply() >= 0);
    }

    // -----------------------------------------------------------------------
    // Property: mint then immediate redeem returns close to original ETH
    //           (only fee is lost, never more).
    // -----------------------------------------------------------------------
    function testProperty_MintRedeemRoundTrip(uint96 amount) public {
        vm.assume(amount > 10000); // avoid zero fee edge-cases
        vm.deal(alice, amount);

        vm.prank(alice);
        ncc.mint{value: amount}();
        assertEq(ncc.balanceOf(alice), amount);

        uint256 before = alice.balance;
        vm.prank(alice);
        ncc.redeem(amount);

        uint256 returned = alice.balance - before;
        uint256 maxFee   = (uint256(amount) * ncc.REDEMPTION_FEE_BPS()) / ncc.BPS_BASE() + 1;
        // Returned + fee == amount (within 1 wei rounding)
        assertGe(returned + maxFee, amount);
        assertLe(returned, amount); // cannot get back more than put in
    }

    // -----------------------------------------------------------------------
    // Property: burnForService only decreases balance, never increases it.
    // -----------------------------------------------------------------------
    function testProperty_BurnForServiceReducesBalance(uint96 mintAmt, uint96 burnAmt) public {
        vm.assume(mintAmt > 0 && burnAmt > 0 && burnAmt <= mintAmt);
        vm.deal(bob, mintAmt);

        vm.prank(bob);
        ncc.mint{value: mintAmt}();
        uint256 balBefore = ncc.balanceOf(bob);

        vm.prank(service);
        ncc.burnForService(bob, burnAmt, "test");

        assertEq(ncc.balanceOf(bob), balBefore - burnAmt);
        assertEq(ncc.agentComputeSpend(bob), burnAmt);
    }
}

/**
 * @notice Invariants for AgentEscrow.
 *
 * These are compiled-in stubs that document expected invariants.
 * Full invariant fuzzing against AgentEscrow requires the contract to be
 * deployed; tests will be activated once AgentEscrow.sol is available.
 */
contract AgentEscrowInvariantsStub is Test {
    // Placeholder — imported once AgentEscrow.sol exists.
    // import {AgentEscrow} from "../../src/AgentEscrow.sol";
    //
    // Invariants to test:
    //   1. insurancePool() only grows (never decreases except via resolveDispute)
    //   2. getJobCount() only grows
    //   3. sum(job.payment for Open jobs) == ETH_balance - insurancePool
    //
    // These will be wired up in a full Foundry invariant campaign.

    function test_Stub() public pure {
        // Documented intent; no-op until AgentEscrow.sol is available.
        assert(true);
    }
}
