// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

/**
 * @title NexusArbiter
 * @notice Alkahest escrow arbiter that uses a Noir ZK proof as its fulfillment
 *         condition. Proves: API call was made with valid key, result matches
 *         a committed hash, and timestamp is within the agreed window.
 *
 * @dev This is a new arbiter type (not a wrapper) for the Alkahest Escrow
 *      Extensions track. Escrow payments are released only on submission of a
 *      valid Noir proof verified by a per-escrow verifier contract.
 *
 *      Mock-verifier mode: when verifier == address(0), any non-empty proof
 *      passes (useful for local testing without a deployed Noir circuit).
 */

// ---------------------------------------------------------------------------
// Interfaces
// ---------------------------------------------------------------------------

/**
 * @notice Minimal Alkahest arbiter interface.
 */
interface IArbiter {
    function arbitrate(bytes32 escrowId, bytes calldata arbitrationData) external returns (bool);
}

/**
 * @notice Noir UltraPlonk / UltraHonk verifier interface generated by `nargo codegen-verifier`.
 *         Public inputs are packed as a flat array of field elements (bytes32).
 */
interface INoirVerifier {
    function verify(bytes calldata proof, bytes32[] calldata publicInputs) external view returns (bool);
}

// ---------------------------------------------------------------------------
// NexusArbiter
// ---------------------------------------------------------------------------

contract NexusArbiter is IArbiter {
    // -----------------------------------------------------------------------
    // Types
    // -----------------------------------------------------------------------

    struct EscrowRecord {
        address verifier;    // Noir verifier contract; address(0) = mock mode
        bytes32 resultHash;  // Committed hash of the API result
        uint256 deadline;    // Unix timestamp — proof must be submitted before this
        bool released;       // True once the escrow has been released
        bool exists;
    }

    // -----------------------------------------------------------------------
    // State
    // -----------------------------------------------------------------------

    address public owner;

    // escrowId => EscrowRecord
    mapping(bytes32 => EscrowRecord) public escrows;

    // -----------------------------------------------------------------------
    // Events
    // -----------------------------------------------------------------------

    event EscrowCreated(
        bytes32 indexed escrowId,
        address indexed verifier,
        bytes32 resultHash,
        uint256 deadline
    );

    event EscrowReleased(
        bytes32 indexed escrowId,
        address indexed caller,
        bytes32[] publicInputs
    );

    event EscrowExpired(bytes32 indexed escrowId);

    // -----------------------------------------------------------------------
    // Modifiers
    // -----------------------------------------------------------------------

    modifier onlyOwner() {
        require(msg.sender == owner, "Not owner");
        _;
    }

    // -----------------------------------------------------------------------
    // Constructor
    // -----------------------------------------------------------------------

    constructor() {
        owner = msg.sender;
    }

    // -----------------------------------------------------------------------
    // Escrow lifecycle
    // -----------------------------------------------------------------------

    /**
     * @notice Register a new escrow record with its Noir verifier and conditions.
     * @param escrowId   Unique identifier for this escrow (e.g. keccak256 of order data).
     * @param verifier   Address of the Noir verifier contract.
     *                   Pass address(0) to enable mock mode (testing only).
     * @param resultHash Committed hash of the expected API result.
     * @param deadline   Unix timestamp after which no new proofs are accepted.
     */
    function createEscrow(
        bytes32 escrowId,
        address verifier,
        bytes32 resultHash,
        uint256 deadline
    ) external {
        require(!escrows[escrowId].exists, "Escrow already exists");
        require(deadline > block.timestamp, "Deadline in the past");

        escrows[escrowId] = EscrowRecord({
            verifier: verifier,
            resultHash: resultHash,
            deadline: deadline,
            released: false,
            exists: true
        });

        emit EscrowCreated(escrowId, verifier, resultHash, deadline);
    }

    /**
     * @notice Submit a Noir ZK proof to release the escrow.
     * @param escrowId     The escrow to release.
     * @param noirProof    Serialised Noir proof bytes.
     * @param publicInputs Public inputs to the circuit. Expected layout:
     *                       [0] = resultHash  (must match stored value)
     *                       [1] = timestampLow (proof timestamp, must be <= deadline)
     *                       [2..] = additional circuit-specific inputs
     * @return true if the proof is valid and the escrow was released.
     */
    function verifyDelivery(
        bytes32 escrowId,
        bytes calldata noirProof,
        bytes32[] calldata publicInputs
    ) external returns (bool) {
        EscrowRecord storage record = escrows[escrowId];
        require(record.exists, "Unknown escrow");
        require(!record.released, "Already released");
        require(block.timestamp <= record.deadline, "Deadline passed");

        bool proofValid;

        if (record.verifier == address(0)) {
            // Mock mode: any non-empty proof is accepted (testing only)
            proofValid = noirProof.length > 0;
        } else {
            // Verify result hash matches the first public input
            if (publicInputs.length < 1) {
                return false;
            }
            if (publicInputs[0] != record.resultHash) {
                return false;
            }

            // Verify timestamp is within window (second public input = proof timestamp)
            if (publicInputs.length >= 2) {
                uint256 proofTimestamp = uint256(publicInputs[1]);
                if (proofTimestamp > record.deadline) {
                    return false;
                }
            }

            // Delegate to the Noir verifier
            proofValid = INoirVerifier(record.verifier).verify(noirProof, publicInputs);
        }

        if (!proofValid) {
            return false;
        }

        record.released = true;
        emit EscrowReleased(escrowId, msg.sender, publicInputs);
        return true;
    }

    /**
     * @notice IArbiter compliance: arbitrate using packed (proof ++ publicInputs).
     *         ABI-encodes (bytes proof, bytes32[] publicInputs) in arbitrationData.
     */
    function arbitrate(bytes32 escrowId, bytes calldata arbitrationData) external override returns (bool) {
        (bytes memory proof, bytes32[] memory publicInputs) =
            abi.decode(arbitrationData, (bytes, bytes32[]));
        return this.verifyDelivery(escrowId, proof, publicInputs);
    }

    // -----------------------------------------------------------------------
    // View helpers
    // -----------------------------------------------------------------------

    /**
     * @notice Returns true if the escrow exists, is not released, and has not passed its deadline.
     */
    function isActive(bytes32 escrowId) external view returns (bool) {
        EscrowRecord storage r = escrows[escrowId];
        return r.exists && !r.released && block.timestamp <= r.deadline;
    }

    /**
     * @notice Returns true if the escrow has been successfully released.
     */
    function isReleased(bytes32 escrowId) external view returns (bool) {
        return escrows[escrowId].released;
    }
}
